package facebooknotifier;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Filip
 */
public class MainDialog extends javax.swing.JFrame {
    private DefaultListModel<FacebookAccount> listModel;
    private ArrayList<FacebookAccount> accounts;
    private Notifyer n;
    private String callpath;
    private final TrayIcon tray;
    
    /** Creates new form MainDialog */
    public MainDialog(final FacebookChecker facebookChecker) {
        this.listModel = new DefaultListModel<FacebookAccount>();
        accounts = facebookChecker.getAccounts();
        for (FacebookAccount facebookAccount : accounts) {
            listModel.addElement(facebookAccount);
        }
        initComponents();
        callpath = callPathField.getText();
        URL imgpath = ClassLoader.getSystemResource("facebooknotifyer/favicon.png");
        Image facebookIco = Toolkit.getDefaultToolkit().getImage(imgpath);
        tray = new TrayIcon(facebookIco, "Facebook Notifier");
        tray.setImageAutoSize(true);
        
        PopupMenu popupMenu = new PopupMenu("Menu");
     
        MenuItem openDialogItem = new MenuItem("Options");
        openDialogItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(true);
            }
        });
        popupMenu.add(openDialogItem);
        
        
        MenuItem exitItem = new MenuItem("Exit");
        exitItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        popupMenu.add(exitItem);
        
        tray.setPopupMenu(popupMenu);
        try {
            SystemTray.getSystemTray().add(tray);
        } catch (AWTException ex) {
            Logger.getLogger(MainDialog.class.getName()).log(Level.SEVERE, "Tray not supported", ex);
        }
        
        n = new Notifyer() {
            @Override
            public void onEvent(String title, String message) {
                tray.displayMessage(title, message, TrayIcon.MessageType.WARNING);
                try {
                    String call = String.format(callpath, message);
                    Runtime.getRuntime().exec(call);
                    Toolkit.getDefaultToolkit().beep();
                    System.out.println(message);
                    tray.setToolTip(message);
                } catch (Exception ex) {
                    //Logger.getLogger(MainDialog.class.getName()).log(Level.INFO, "Bad callpath entered", ex);
                }
            }

            @Override
            public void onCheck(String time) {}

            @Override
            public void onStatusChange(StatusType status) {}
        };
        
        FacebookChecker checker = new FacebookChecker(accounts);
        checker.addNotifyer(n);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        callPathField = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        formatHelpLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountListView = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Facebook Notifier");

        accountLabel.setText("Your Facebook accounts");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        callPathField.setText("C:\\nirCmd.exe speak text \"%s\"");
        callPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callPathFieldActionPerformed(evt);
            }
        });

        pathLabel.setLabelFor(callPathField);
        pathLabel.setText("Runnable path");

        formatHelpLabel.setText("%s will transform to the notifcation text");

        accountListView.setModel(listModel);
        jScrollPane2.setViewportView(accountListView);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add (id,key)");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Add (RSS)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(accountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(formatHelpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addComponent(callPathField, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(pathLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLabel)
                    .addComponent(removeButton)
                    .addComponent(addButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(callPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formatHelpLabel)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    FacebookNotifyerApp.saveSettings(accounts);
    setVisible(false);
}//GEN-LAST:event_saveButtonActionPerformed

private void callPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callPathFieldActionPerformed
    
}//GEN-LAST:event_callPathFieldActionPerformed

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    String id = JOptionPane.showInputDialog(rootPane, "Enter id\n This is found in the Facebook notification center via the RSS-option and its GET string");
    if (id == null || id.trim().isEmpty()) {
        return;
    }
    String key = JOptionPane.showInputDialog(rootPane, "Enter key");
    if (key == null || key.trim().isEmpty()) {
        return;
    }
    FacebookAccount fa = new FacebookAccount(id, key);
    accounts.add(fa);
    listModel.addElement(fa);
}//GEN-LAST:event_addButtonActionPerformed

private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
    accounts.remove(accountListView.getSelectedIndex());
    listModel.remove(accountListView.getSelectedIndex());
}//GEN-LAST:event_removeButtonActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String get = JOptionPane.showInputDialog(rootPane, "Enter id\n This is found in the Facebook notification center via the RSS-option and its GET string");
    if (get == null || get.trim().isEmpty()) {
        return;
    }
    int startId = get.indexOf("id=")+3;
    int endId = get.indexOf("&",startId);
    String id = get.substring(startId,endId);
    
    int startKey = get.indexOf("key=")+4;
    int endKey = get.indexOf("&",startKey);
    String key = get.substring(startKey,endKey);
    JOptionPane.showMessageDialog( rootPane, "Your id: "+ id +"\nYour key: " + key + "\nYour account was added" );
    FacebookAccount fa = new FacebookAccount(id, key);
    accounts.add(fa);
    listModel.addElement(fa);
}//GEN-LAST:event_jButton1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JList accountListView;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField callPathField;
    private javax.swing.JLabel formatHelpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
